GET http://localhost:8080/api/users

###

# Variable for user ID
@userId = 4fea194e-0834-4b94-810f-3112b959de0d

###

# Get user by ID
GET http://localhost:8080/api/user/{{userId}}
# GET http://localhost:8080/api/user/1234

###

# Get balance user
GET http://localhost:8080/api/user/{{userId}}/balance

###

# Create a new user
POST http://localhost:8080/api/user
content-type: application/json

{
    "first_name": "Amanda",
    "last_name": "Tavares",
    "email": "amanda@fsc.com",
    "password": "1q2w3e"
}

###

# Update user by ID
PATCH  http://localhost:8080/api/user/{{userId}}
content-type: application/json

{
    "email": "gt3oliveira@fsc.com",
    "password" : "1q2w3e"
}

###

# Delete user by ID
DELETE http://localhost:8080/api/user/{{userId}}
