# Variable for user ID
@jwtToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0ZmVhMTk0ZS0wODM0LTRiOTQtODEwZi0zMTEyYjk1OWRlMGQiLCJpYXQiOjE3NTU4MTMyMTcsImV4cCI6MTc1NTgxNDExN30.lVw85NCsmimikbBTIb2cmLziqHaJYy483wkHuV0j6F4
@transactionId = ecbd7b10-f1ce-462d-a36c-5f06e5d82d97

###

# Get transaction by ID
GET http://localhost:8080/api/transactions
# GET http://localhost:8080/api/user/1234
Authorization: Bearer {{jwtToken}}

###

# Create a new transaction
POST http://localhost:8080/api/transactions
Authorization: Bearer {{jwtToken}}
content-type: application/json

{
    "name": "Salário",
    "date": "2025-08-02T00:00:00.000Z",
    "amount": 5000,
    "type": "EARNING"
}

// ['EARNING', 'EXPENSE', 'INVESTMENT']
###

# Update transaction by ID
PATCH  http://localhost:8080/api/transactions/{{transactionId}}
Authorization: Bearer {{jwtToken}}
content-type: application/json

{
    "name": "Trade Stocks Updated"
}

// ['EARNING', 'EXPENSE', 'INVESTMENT']
###

# Delete transaction by ID
DELETE http://localhost:8080/api/transactions/{{transactionId}}
