GET http://localhost:8080/api/users

###

# Variable for user ID
@userId = 4fea194e-0834-4b94-810f-3112b959de0d

###

# Get user by ID
GET http://localhost:8080/api/user/{{userId}}
# GET http://localhost:8080/api/user/1234
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0ZmVhMTk0ZS0wODM0LTRiOTQtODEwZi0zMTEyYjk1OWRlMGQiLCJpYXQiOjE3NTU4MDAzNzQsImV4cCI6MTc1NTgwMTI3NH0.wKXt4ISg-Ecf25DR7N4LnMrGVaYGWIUPaQKgD_7eONk

###

# Get balance user
GET http://localhost:8080/api/user/{{userId}}/balance
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0ZmVhMTk0ZS0wODM0LTRiOTQtODEwZi0zMTEyYjk1OWRlMGQiLCJpYXQiOjE3NTU4MDAzNzQsImV4cCI6MTc1NTgwMTI3NH0.wKXt4ISg-Ecf25DR7N4LnMrGVaYGWIUPaQKgD_7eONk
###

# Create a new user
POST http://localhost:8080/api/user
content-type: application/json

{
    "first_name": "Amanda",
    "last_name": "Tavares",
    "email": "amanda@fsc.com",
    "password": "1q2w3e"
}

###

# Update user by ID
PATCH  http://localhost:8080/api/user/{{userId}}
content-type: application/json

{
    "email": "gt3oliveira@fsc.com",
    "password" : "1q2w3e"
}

###
# Login user
POST http://localhost:8080/api/user/login
content-type: application/json

{
    "email": "gt3oliveira@fsc.com",
    "password": "1q2w3e"
}

###

# Delete user by ID
DELETE http://localhost:8080/api/user/{{userId}}
