GET http://localhost:8080/api/users

###

# Variable for user ID
# @userId = 4fea194e-0834-4b94-810f-3112b959de0d
@jwtToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0ZmVhMTk0ZS0wODM0LTRiOTQtODEwZi0zMTEyYjk1OWRlMGQiLCJpYXQiOjE3NTU4MTAwNTEsImV4cCI6MTc1NTgxMDk1MX0.28Q538Ctmlt7Avmrp_3PGQPInoum55Ik1OueTd86WhI

###

# Get user by ID
GET http://localhost:8080/api/user
# GET http://localhost:8080/api/user/1234
Authorization: Bearer {{jwtToken}}

###

# Get balance user
GET http://localhost:8080/api/user/balance
Authorization: Bearer {{jwtToken}}
###

# Create a new user
POST http://localhost:8080/api/user
content-type: application/json

{
    "first_name": "John",
    "last_name": "Dee",
    "email": "john@fsc.com",
    "password": "1q2w3e"
}

###

# Update user by ID
PATCH  http://localhost:8080/api/user
Authorization: Bearer {{jwtToken}}
content-type: application/json

{
    "email": "gt3@fsc.com",
    "password" : "1q2w3e"
}

###
# Login user
POST http://localhost:8080/api/user/login
content-type: application/json

{
    "email": "gt3@fsc.com",
    "password": "1q2w3e"
}

###
POST http://localhost:8080/api/user/refresh-token
content-type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0ZmVhMTk0ZS0wODM0LTRiOTQtODEwZi0zMTEyYjk1OWRlMGQiLCJpYXQiOjE3NTU4OTkxMTUsImV4cCI6MTc1ODQ5MTExNX0.rMbt8_bk5TQprGj4O1sIjZrdY-N72mMzKgru8e-BTC0"
}
###

# Delete user by ID
DELETE http://localhost:8080/api/user
Authorization: Bearer {{jwtToken}}
