# Variable for user ID
@userId = 4fea194e-0834-4b94-810f-3112b959de0d
@transactionId = 68522b8a-488d-4e19-9965-ae63e1b2c329

###

# Get transaction by ID
GET http://localhost:8080/api/transactions?userId={{userId}}
# GET http://localhost:8080/api/user/1234

###

# Create a new transaction
POST http://localhost:8080/api/transactions
content-type: application/json

{
    "user_id": "4fea194e-0834-4b94-810f-3112b959de0d",
    "name": "Betano",
    "date": "2025-08-02T00:00:00.000Z",
    "amount": 600,
    "type": "INVESTMENT"
}

// ['EARNING', 'EXPENSE', 'INVESTMENT']
###

# Update transaction by ID
PATCH  http://localhost:8080/api/transactions/{{transactionId}}
content-type: application/json

{
    "amount": 5000
}

// ['EARNING', 'EXPENSE', 'INVESTMENT']
###

# Delete transaction by ID
DELETE http://localhost:8080/api/transactions/{{transactionId}}
